### [findAll] Retorna todos os registros de empresas ###
GET http://localhost:3333/v1/roles HTTP/1.1
User-Agent: rest-client

### [findOne] Retorna uma empresa em específico ###
GET http://localhost:3333/v1/roles/1 HTTP/1.1
User-Agent: rest-client

### [create] Adiciona uma nova regra na base de dados ###
POST http://localhost:3333/v1/roles HTTP/1.1
User-Agent: rest-client
content-type: application/json

{
  "name": "Collaborator Role",
  "description": "Contain collaborator permissions",
  "permissions": [
    "PERMISSION_01",
    "PERMISSION_02",
    "PERMISSION_03",
    "PERMISSION_04",
    "PERMISSION_05"
  ]
}

### [update] Atualiza as informações de uma empresa já existente ###
PATCH http://localhost:3333/v1/roles/1 HTTP/1.1
User-Agent: rest-client
content-type: application/json

### [destroy] Deleta da base de dados uma empresa previamente cadastrado ###
DELETE http://localhost:3333/v1/roles/1 HTTP/1.1
